name: Deploy NMS

on:
  push:
    paths:
      - 'docker/nms/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Ansible for NMS
        run: |
          ansible-playbook docker/deploy/deploy.yml \
            -i docker/deploy/inventory.ini \
            --limit nms \
            -e "target=nms"
