name: Deploy Radius

on:
  push:
    paths:
      - 'docker/radius/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted          # 172.16.10.15 Runner 받음

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Ansible for Radius
        env:
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
        run: |
          ansible-playbook docker/deploy/deploy.yml \
          -i docker/deploy/inventory.ini \
          --limit radius \
          -e "target=radius" \
          --vault-password-file <(echo "$VAULT_PASSWORD")
